const actionNames = {

  FETCH_HOTELS: 'FETCH_HOTELS',
  FETCH_SERVICES: 'FETCH_SERVICES',
  SUCCESS_HOTELS: 'SUCCESS_HOTELS',
  SUCCESS_SERVICES: 'SUCCESS_SERVICES',
  SUCCESS_AUTH: 'SUCCESS_AUTH',
  FAIL: 'FAIL',
  SUCCESS_VOTE: 'SUCCESS_VOTE',
  VOTE: 'VOTE',
  POPUP: 'POPUP',
  RATE: 'RATE',
  CANSEL_VOTE: 'CANSEL_VOTE',
  AUTH: 'AUTH',
  SUCCESS_LOGOUT: 'SUCCESS_LOGOUT',
  LOGOUT: 'LOGOUT',
  SEARCH: 'SEARCH',
};
export default actionNames;
